CREATE TABLE PUBLIC.user (id INT AUTO_INCREMENT NOT NULL,
first_name VARCHAR(30), 
last_name VARCHAR(30), 
role VARCHAR(30), 
email VARCHAR(30) NOT NULL, 
last_login time, 
is_active BOOLEAN DEFAULT FALSE NOT NULL, 
pass VARCHAR(200), 
activationid VARCHAR(100), 
uuid VARCHAR(43) NOT NULL, 
CONSTRAINT PK_USER PRIMARY KEY (id),
UNIQUE (activationid), 
UNIQUE (email))